Repository jupyterlab-contrib/jupyterlab-js-logs, pull requests merged in 2021-09, with the labels that each got.

#11 Remove circular references when stringifying an object
  src/index.ts
Labels: bug

#12 Add github action to check release
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .gitignore
  .prettierignore
  .vscode/settings.json
  CHANGELOG.md
  MANIFEST.in
  README.md
  RELEASE.md
  install.json
  jupyterlab_js_logs/__init__.py
  jupyterlab_js_logs/_version.py
  package.json
  pyproject.toml
  setup.py
Labels: maintenance

#13 Add `publishConfig` to `package.json`
  package.json
Labels: maintenance

#16 Update Binder link to point to the `main` branch
  README.md
Labels: documentation
